MOD_ENABLE DXT_POSIX
OUTPUT_MODE security

# Default exclude paths (reproducing Darshan exclusions)
EXCLUDE_PATH /etc/
EXCLUDE_PATH /dev/
EXCLUDE_PATH /usr/
EXCLUDE_PATH /bin/
EXCLUDE_PATH /boot/
EXCLUDE_PATH /lib/
EXCLUDE_PATH /opt/
EXCLUDE_PATH /sbin/
EXCLUDE_PATH /sys/
EXCLUDE_PATH /proc/
EXCLUDE_PATH /var/
